name: Update LeetCode Stats

on:
  schedule:
    - cron: '0 0 * * *' # Run daily
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch LeetCode Stats
        run: |
          pip install requests
          python fetch_leetcode_stats.py

      - name: Update README
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Updated LeetCode stats"
          git push
